### ISSUE TITLE
Home Page: Sponsors Section

### ISSUE THREAD

**Issue by pattyok** [iandunn/wordcamp-seattle-2019#5]
https://wordcampseattleplanning.files.wordpress.com/2019/04/homepage-80-1.jpg

**Comment by iandunn** [comment]
Gutenberg hasn't added the ability to add blocks into widget areas yet (or however that will happen), so I think we'll need to use the older Sponsors widget [if this should be part of the footer](https://trello.com/c/6Pi5WE93/83-design-website-wireframes#comment-5ce05833583b488303d8a41c).

If it'll be part of the home page content, though, it'd probably be better to use the new Sponsors block. The [CSS class names will change shortly](https://github.com/WordPress/wordcamp.org/issues/96), and we'll need to opt-in to beta-testing the new blocks.

**Comment by pattyok** [comment]
Since it is the last thing on the page it can be placed into the Widget area (#5) or as a block in the content section...

**Comment by iandunn** [comment]
FYI: The Sponsors, Speakers, Sessions, and Organizers blocks are enabled on our site for beta-testing now.

x-ref: https://make.wordpress.org/community/2019/05/29/who-wants-to-test-the-new-wordcamp-blocks/

**Comment by iandunn** [comment]
I think this is close enough, we can iterate if the team requests any changes.
